export const CDSABI = [
  {
    inputs: [
      { internalType: "address", name: "_amint", type: "address" },
      { internalType: "address", name: "priceFeed", type: "address" },
      { internalType: "address", name: "_usdt", type: "address" },
      { internalType: "address", name: "_multiSign", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint128",
        name: "depositedAmint",
        type: "uint128",
      },
      { indexed: false, internalType: "uint64", name: "index", type: "uint64" },
      {
        indexed: false,
        internalType: "uint128",
        name: "liquidationAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "normalizedAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "depositVal",
        type: "uint128",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint128",
        name: "withdrewAmint",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "withdrawETH",
        type: "uint128",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [],
    name: "PRECISION",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "amint",
    outputs: [{ internalType: "contract IAMINT", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "amintLimit",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowing",
    outputs: [
      { internalType: "contract IBorrowing", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowingContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "burnedAmintInRedeem",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "fees", type: "uint128" }],
    name: "calculateCumulativeRate",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cdsCount",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "cdsDetails",
    outputs: [
      { internalType: "uint64", name: "index", type: "uint64" },
      { internalType: "bool", name: "hasDeposited", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cumulativeValue",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cumulativeValueSign",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint128", name: "usdtAmount", type: "uint128" },
      { internalType: "uint128", name: "amintAmount", type: "uint128" },
      { internalType: "bool", name: "_liquidate", type: "bool" },
      { internalType: "uint128", name: "_liquidationAmount", type: "uint128" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ethVault",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fallbackEthPrice",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "uint64", name: "index", type: "uint64" },
    ],
    name: "getCDSDepositDetails",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "depositedTime", type: "uint64" },
          { internalType: "uint128", name: "depositedAmount", type: "uint128" },
          { internalType: "uint64", name: "withdrawedTime", type: "uint64" },
          {
            internalType: "uint128",
            name: "withdrawedAmount",
            type: "uint128",
          },
          { internalType: "bool", name: "withdrawed", type: "bool" },
          { internalType: "uint128", name: "depositPrice", type: "uint128" },
          { internalType: "uint128", name: "depositValue", type: "uint128" },
          { internalType: "bool", name: "depositValueSign", type: "bool" },
          { internalType: "bool", name: "optedLiquidation", type: "bool" },
          {
            internalType: "uint128",
            name: "InitialLiquidationAmount",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidationAmount",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "liquidationindex",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "normalizedAmount",
            type: "uint128",
          },
        ],
        internalType: "struct CDS.CdsAccountDetails",
        name: "",
        type: "tuple",
      },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastCumulativeRate",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastEthPrice",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint128", name: "liquidationIndex", type: "uint128" },
    ],
    name: "liquidationIndexToInfo",
    outputs: [
      { internalType: "uint128", name: "liquidationAmount", type: "uint128" },
      { internalType: "uint128", name: "profits", type: "uint128" },
      { internalType: "uint128", name: "ethAmount", type: "uint128" },
      {
        internalType: "uint256",
        name: "availableLiquidationAmount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "multiSign",
    outputs: [
      { internalType: "contract IMultiSign", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint128", name: "_amintAmount", type: "uint128" },
      { internalType: "uint64", name: "amintPrice", type: "uint64" },
      { internalType: "uint64", name: "usdtPrice", type: "uint64" },
    ],
    name: "redeemUSDT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "percent", type: "uint8" }],
    name: "setAmintLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "setBorrowingContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_treasury", type: "address" }],
    name: "setTreasury",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "amount", type: "uint64" }],
    name: "setUsdtLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "_timeLimit", type: "uint64" }],
    name: "setWithdrawTimeLimit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAvailableLiquidationAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCdsDepositedAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalCdsDepositedAmountWithOptionFees",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "treasury",
    outputs: [
      { internalType: "contract ITreasury", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasuryAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint128", name: "index", type: "uint128" },
      {
        components: [
          {
            internalType: "uint128",
            name: "liquidationAmount",
            type: "uint128",
          },
          { internalType: "uint128", name: "profits", type: "uint128" },
          { internalType: "uint128", name: "ethAmount", type: "uint128" },
          {
            internalType: "uint256",
            name: "availableLiquidationAmount",
            type: "uint256",
          },
        ],
        internalType: "struct CDS.LiquidationInfo",
        name: "liquidationData",
        type: "tuple",
      },
    ],
    name: "updateLiquidationInfo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "updateTotalAvailableLiquidationAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "_amount", type: "uint128" }],
    name: "updateTotalCdsDepositedAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint128", name: "_amount", type: "uint128" }],
    name: "updateTotalCdsDepositedAmountWithOptionFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdt",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdtAmountDepositedTillNow",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdtLimit",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "_index", type: "uint64" }],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawTimeLimit",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
