export const TreasuryAbi = [
  {
    inputs: [
      { internalType: "address", name: "_borrowing", type: "address" },
      { internalType: "address", name: "_tokenAddress", type: "address" },
      { internalType: "address", name: "_cdsContract", type: "address" },
      { internalType: "address", name: "_wethGateway", type: "address" },
      { internalType: "address", name: "_cEther", type: "address" },
      {
        internalType: "address",
        name: "_aavePoolAddressProvider",
        type: "address",
      },
      { internalType: "address", name: "_aToken", type: "address" },
      { internalType: "address", name: "_usdt", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  { inputs: [], name: "Treasury_AaveDepositAndMintFailed", type: "error" },
  { inputs: [], name: "Treasury_AavePoolAddressZero", type: "error" },
  { inputs: [], name: "Treasury_AaveWithdrawFailed", type: "error" },
  { inputs: [], name: "Treasury_CompoundDepositAndMintFailed", type: "error" },
  { inputs: [], name: "Treasury_CompoundWithdrawFailed", type: "error" },
  {
    inputs: [],
    name: "Treasury_EthTransferToCdsLiquidatorFailed",
    type: "error",
  },
  { inputs: [], name: "Treasury_ZeroDeposit", type: "error" },
  { inputs: [], name: "Treasury_ZeroWithdraw", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint64", name: "count", type: "uint64" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DepositToAave",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint64", name: "count", type: "uint64" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DepositToCompound",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "user", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint64", name: "count", type: "uint64" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawFromAave",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint64", name: "count", type: "uint64" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "WithdrawFromCompound",
    type: "event",
  },
  {
    inputs: [],
    name: "aToken",
    outputs: [{ internalType: "contract IATOKEN", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "aavePoolAddressProvider",
    outputs: [
      {
        internalType: "contract IPoolAddressesProvider",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "aaveWETH",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_address", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "approveAmint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_address", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "approveUsdt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "borrow",
    outputs: [
      { internalType: "contract IBorrowing", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "depositor", type: "address" }],
    name: "borrowing",
    outputs: [
      { internalType: "uint256", name: "depositedAmount", type: "uint256" },
      { internalType: "uint256", name: "totalBorrowedAmount", type: "uint256" },
      { internalType: "bool", name: "hasBorrowed", type: "bool" },
      { internalType: "bool", name: "hasDeposited", type: "bool" },
      { internalType: "uint64", name: "borrowerIndex", type: "uint64" },
      { internalType: "uint128", name: "totalPTokens", type: "uint128" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "borrowingContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cEther",
    outputs: [{ internalType: "contract ICEther", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "cdsContract",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "compoundAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "uint128", name: "_ethPrice", type: "uint128" },
      { internalType: "uint64", name: "_depositTime", type: "uint64" },
    ],
    name: "deposit",
    outputs: [
      { internalType: "bool", name: "", type: "bool" },
      { internalType: "uint64", name: "", type: "uint64" },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositToAave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositToCompound",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getBalanceInTreasury",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "uint64", name: "index", type: "uint64" },
    ],
    name: "getBorrowing",
    outputs: [
      { internalType: "uint64", name: "", type: "uint64" },
      {
        components: [
          { internalType: "uint64", name: "depositedTime", type: "uint64" },
          { internalType: "uint128", name: "depositedAmount", type: "uint128" },
          {
            internalType: "uint64",
            name: "downsidePercentage",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "ethPriceAtDeposit",
            type: "uint128",
          },
          { internalType: "uint128", name: "borrowedAmount", type: "uint128" },
          {
            internalType: "uint128",
            name: "normalizedAmount",
            type: "uint128",
          },
          { internalType: "uint8", name: "withdrawNo", type: "uint8" },
          { internalType: "bool", name: "withdrawed", type: "bool" },
          { internalType: "uint128", name: "withdrawAmount", type: "uint128" },
          { internalType: "bool", name: "liquidated", type: "bool" },
          {
            internalType: "uint64",
            name: "ethPriceAtWithdraw",
            type: "uint64",
          },
          { internalType: "uint64", name: "withdrawTime", type: "uint64" },
          { internalType: "uint128", name: "pTokensAmount", type: "uint128" },
          { internalType: "uint64", name: "strikePrice", type: "uint64" },
        ],
        internalType: "struct Treasury.DepositDetails",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "noOfBorrowers",
    outputs: [{ internalType: "uint128", name: "", type: "uint128" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "enum Treasury.Protocol", name: "", type: "uint8" },
    ],
    name: "protocolDeposit",
    outputs: [
      { internalType: "uint64", name: "depositIndex", type: "uint64" },
      { internalType: "uint256", name: "depositedAmount", type: "uint256" },
      { internalType: "uint256", name: "totalCreditedTokens", type: "uint256" },
      { internalType: "uint256", name: "depositedUsdValue", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "setBorrowingContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalInterest",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalInterestFromLiquidation",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalVolumeOfBorrowersAmountinUSD",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalVolumeOfBorrowersAmountinWei",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "transferEthToCdsLiquidators",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "trinity",
    outputs: [
      { internalType: "contract ITrinityToken", name: "", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "depositor", type: "address" },
      { internalType: "uint64", name: "index", type: "uint64" },
      {
        components: [
          { internalType: "uint64", name: "depositedTime", type: "uint64" },
          { internalType: "uint128", name: "depositedAmount", type: "uint128" },
          {
            internalType: "uint64",
            name: "downsidePercentage",
            type: "uint64",
          },
          {
            internalType: "uint128",
            name: "ethPriceAtDeposit",
            type: "uint128",
          },
          { internalType: "uint128", name: "borrowedAmount", type: "uint128" },
          {
            internalType: "uint128",
            name: "normalizedAmount",
            type: "uint128",
          },
          { internalType: "uint8", name: "withdrawNo", type: "uint8" },
          { internalType: "bool", name: "withdrawed", type: "bool" },
          { internalType: "uint128", name: "withdrawAmount", type: "uint128" },
          { internalType: "bool", name: "liquidated", type: "bool" },
          {
            internalType: "uint64",
            name: "ethPriceAtWithdraw",
            type: "uint64",
          },
          { internalType: "uint64", name: "withdrawTime", type: "uint64" },
          { internalType: "uint128", name: "pTokensAmount", type: "uint128" },
          { internalType: "uint64", name: "strikePrice", type: "uint64" },
        ],
        internalType: "struct Treasury.DepositDetails",
        name: "depositDetail",
        type: "tuple",
      },
    ],
    name: "updateDepositDetails",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "bool", name: "_bool", type: "bool" },
    ],
    name: "updateHasBorrowed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "updateTotalBorrowedAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "updateTotalDepositedAmount",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "updateTotalInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "updateTotalInterestFromLiquidation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "updateTotalPTokensDecrease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "uint128", name: "amount", type: "uint128" },
    ],
    name: "updateTotalPTokensIncrease",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "usdt",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "wethGateway",
    outputs: [
      {
        internalType: "contract IWrappedTokenGatewayV3",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "borrower", type: "address" },
      { internalType: "address", name: "toAddress", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
      { internalType: "uint64", name: "index", type: "uint64" },
      { internalType: "uint64", name: "_ethPrice", type: "uint64" },
    ],
    name: "withdraw",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "index", type: "uint64" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawFromAave",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "index", type: "uint64" }],
    name: "withdrawFromCompound",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "toAddress", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "withdrawInterest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
