import { Button } from "@/components/ui/button";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderItems from "@/components/Header/HeaderItems";
import SideBar from "@/components/Sidebar/SideBar";
import Image from "next/image";
import { Toaster } from "sonner";
import showMore from "@/app/assets/arrow_circle_down.svg";

const inter = Inter({ subsets: ["latin"] });
const headerItems = [
  {
    headline: "AMINT Price",
    value: "$1.023",
  },
  {
    headline: "ABOND Price",
    value: "$1.012",
  },
  {
    headline: "AMINT Supply",
    value: "$1M",
  },
  {
    headline: "Current APY",
    value: "5%",
  },
  {
    headline: "Options Fees",
    value: "3%",
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="grid min-h-screen grid-cols-[140px_1fr]">
          <SideBar />
          <div className="h-full bg-bgGrey flex flex-col pb-6 pr-6">
            <div className="flex px-4 py-5">
              {headerItems.map((item, index) => (
                <HeaderItems
                  key={index}
                  props={{ textHeadline: item.headline, textValue: item.value }}
                />
              ))}
              <Button
                variant={"showMore"}
                className="px-4 pb-4 py-0 flex flex-col gap-[10px] items-center h-full"
              >
                <Image src={showMore} alt="show more" width={35} height={35} />
                <p className="text-borderGrey text-base font-medium whitespace-nowrap">
                  Show More
                </p>
              </Button>
            </div>
            {children}
          </div>
        </main>
        <Toaster
          duration={10000}
          richColors
          closeButton={true}
          position="top-center"
        />
      </body>
    </html>
  );
}
